### ISSUE TITLE
Can't setup the database 

### ISSUE THREAD

**Issue by dominikmi** [cisagov/decider#15]
# 🐛 Summary #

Ubuntu 20.04, Python 3.8.10; After successfully installing all required packages to ultimately installing all the python requirements in `requirements.txt` and `requirements_dev.txt`, I am not able to setup the database with the step mentioned in the Admin Guide (page: 12)

```console
(venv)~/CISA/decider$ sudo -u decider python3 initial_setup.py
Traceback (most recent call last):
  File "initial_setup.py", line 3, in <module>
    import dotenv
ModuleNotFoundError: No module named 'dotenv'
```

and the package `dotenv` cannot be installed for some reason (no matter if I clean up `pip` cache or not):

```console
(venv)~/CISA/decider$ python -m pip install dotenv
Collecting dotenv
  Using cached dotenv-0.0.5.tar.gz (2.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
        error: subprocess-exited-with-error

        × python setup.py egg_info did not run successfully.
        │ exit code: 1
        ╰─> [16 lines of output]
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 14, in <module>
              File "/tmp/pip-wheel-3yb12le_/distribute_5011ef5ea61a4abb99ab7ca0e1d255e2/setuptools/__init__.py", line 2, in <module>
                from setuptools.extension import Extension, Library
              File "/tmp/pip-wheel-3yb12le_/distribute_5011ef5ea61a4abb99ab7ca0e1d255e2/setuptools/extension.py", line 5, in <module>
                from setuptools.dist import _get_unpatched
              File "/tmp/pip-wheel-3yb12le_/distribute_5011ef5ea61a4abb99ab7ca0e1d255e2/setuptools/dist.py", line 7, in <module>
                from setuptools.command.install import install
              File "/tmp/pip-wheel-3yb12le_/distribute_5011ef5ea61a4abb99ab7ca0e1d255e2/setuptools/command/__init__.py", line 8, in <module>
                from setuptools.command import install_scripts
              File "/tmp/pip-wheel-3yb12le_/distribute_5011ef5ea61a4abb99ab7ca0e1d255e2/setuptools/command/install_scripts.py", line 3, in <module>
                from pkg_resources import Distribution, PathMetadata, ensure_directory
              File "/tmp/pip-wheel-3yb12le_/distribute_5011ef5ea61a4abb99ab7ca0e1d255e2/pkg_resources.py", line 1518, in <module>
                register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
            AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
            [end of output]
```

**Comment by tehfunk101** [comment]
Try running this instead, I ran into the same issue:
python -m pip install python_dotenv

**Comment by damionmounts** [comment]
Interested in hearing if @tehfunk101's solution works for you.

Installing `wheel==0.37.1` before `pip install -r requirements.txt` might work as well.
- That is mentioned in the requirements file as a comment _(a bit obtuse)_
- Apparently upgrading setuptools may help as well

**Comment by dominikmi** [comment]
> python -m pip install python_dotenv

nope.. it didn't help. I tried that before and have tried again now:
```console
(venv)~/CISA/decider$ python -m pip install python_dotenv
Collecting python_dotenv
  Downloading python_dotenv-1.0.0-py3-none-any.whl (19 kB)
Installing collected packages: python_dotenv
Successfully installed python_dotenv-1.0.0
(venv):~/CISA/decider$ sudo -u decider python3 initial_setup.py
Traceback (most recent call last):
  File "initial_setup.py", line 3, in <module>
    import dotenv
ModuleNotFoundError: No module named 'dotenv'
```
@damionmounts : I'll start all over again from the scratch on other Ubuntu VM.
These are my steps which brought me to this point:
```console
   96  git clone https://github.com/cisagov/decider.git
   97  cd decider/
   98  ls
   99  ls -l
  100  python3 --version
  101  apt-get install libxml2-dev  libxslt-dev
  102  sudo apt-get install libxml2-dev  libxslt-dev
  103  which pg_config
  104  apt-get install postgresql-dev postgresql
  105  sudo apt-get install postgresql-dev postgresql
  106  sudo apt install python3-dev libpq-dev
  107  python3 -m venv venv/
  108  sudo apt install python3.8-venv
  109  python3 -m venv venv/
  110  source venv/bin/activate
  111  pip3 install wheel==0.37.1
  112  pip3 install -r requirements.txt
  113  sudo apt-get install gcc
  114  pip3 install -r requirements.txt
  115  pip3 install -r requirements_dev.txt
  116  sudo apt install -y git python3-pip python3-testresources libssl-dev
  117  sudo adduser --no-create-home --system --shell /bin/false decider && sudo usermod -L decider
  118  sudo groupadd decider && sudo usermod -aG decider decider
  119  sudo apt install -y postgresql postgresql-contrib
  120  sudo systemctl start postgresql && sudo systemctl enable postgresql
```

**Comment by damionmounts** [comment]
In my test virtual env (through pyenv) `pip freeze` gives:
```
python-dotenv==1.0.0
```

---

As user:
```
python3
>>> import dotenv
```
Works

---

As root / through sudo:
```
sudo python3
>>> import dotenv
ModuleNotFoundError: No module named 'dotenv'
```
Has the same error

_**sudo isn't carrying over the environment that is sourced**_

---

Manually providing interpreter path:
```
sudo /home/damion/.pyenv/versions/3.8.10/envs/install_test-3.8.10/bin/python3
>>> import dotenv
```
Works

---

**I need to update the instructions.**
The original install steps were done with pip packages installed globally - thus no environment issues.
The recommendation to use an environment now causes these instructions to fail.

`sudo -E` may help in environment preservation.
Or just manually providing the interpreter path for `sudo python XYZ` steps.
(as for uWSGI itself - you can specify what virtualenv to be used, **very bottom of the Admin Guide**)

**If you're just running this locally for yourself and not a group:**
Feel free to just do everything as user.
This is all local, no need to fiddle with uWSGI for a production setup over Flask.
You can even just launch with `python decider.py --config <CONF_NAME>`

**Comment by dominikmi** [comment]
Thanks a lot Damion. I will give it another shot this weekend.

**Comment by damionmounts** [comment]
**Long time no see - sorry on that!**

It's for a newer version and includes compiling a dedicated install of Python - but have some much nicer Ubuntu install instructions: https://github.com/cisagov/decider/blob/develop/docs/install/Ubuntu_22.04.2.md

CentOS instructions got updated as well
